[tool.poetry]
name = "unique_orchestrator"
version = "1.4.3"
description = ""
authors = ["Andreas Hauri <andreas.hauri@unique.ai>"]
readme = ["README.md", "CHANGELOG.md"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.12"
typing-extensions = "^4.9.0"
pydantic = "^2.8.2"
pydantic-settings = "^2.10.1"
python-dotenv = "^1.0.1"
pytest = "^8.4.1"
unique-sdk = "^0.10.24"

unique-toolkit = "^1.16.1"
unique-stock-ticker = "^1.0.2"
unique-follow-up-questions = "^1.1.2"
unique-internal-search = "^1.0.1"
unique-deep-research = "^3.0.0"
unique-web-search = "^1.3.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.12.10"
python = "^3.12"
typing-extensions = "^4.9.0"
pydantic = "^2.8.2"
pydantic-settings = "^2.10.1"
python-dotenv = "^1.0.1"
pytest = "^8.4.1"
unique-sdk = { path = "../unique_sdk" }
unique-toolkit = { path = "../unique_toolkit", develop = true }
unique-stock-ticker = { path = "../postprocessors/unique_stock_ticker", develop = true }
unique-follow-up-questions = { path = "../postprocessors/unique_follow_up_questions", develop = true }
unique-internal-search = { path = "../tool_packages/unique_internal_search", develop = true }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = ["I"]
