[project]
name = "mcp-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cedric Klinkert", email = "cedric@unique.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.2",
    "fastmcp>=2.13.0.2",
    "pydantic>=2.12.3",
    "unique-mcp>=0.1.1",
    "unique-toolkit>=1.34.1",
]

[project.scripts]
mcp-template = "mcp_template:main"

[build-system]
requires = ["uv_build>=0.8.23,<0.9.0"]
build-backend = "uv_build"
