[tool.poetry]
name = "unique_stock_ticker"
version = "1.0.8"
description = ""
authors = [
    "Martin Fadler <martin.fadler@unique.ch>",
    "Sadique Sheik <sadique@unique.ch>",
    "Fabian Schl√§pfer <fabian@unique.ch>",
    "Pascal Hauri <pascal@unique.ch>",
]
readme = ["README.md", "CHANGELOG.md"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.8.2"
typing-extensions = "^4.9.0"
unique-toolkit = "^1.38.3"
plotly = "^5.24.1"
numerize = "^0.12"
requests = "^2.32.0"
urllib3 = "^2.0.0"
pyhumps = "^3.8.0"
cryptography = "^45.0.6"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-asyncio = "^0.25.0"
unique-sdk = { path = "../../unique_sdk" }
unique-toolkit = { path = "../../unique_toolkit" }
ruff = "^0.12.10"
deptry = "^0.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.deptry]
known_first_party = ["unique_stock_ticker", "settings"]
extend_exclude = ["unique_stock_ticker/detection/tests"]

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = ["I"]
