[project]
name = "console-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cedric Klinkert", email = "cedric@unique.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.2",
    "pydantic>=2.12.5",
    "pydantic-ai>=1.30.1",
    "pydantic-settings>=2.12.0",
    "rich>=14.2.0",
    "unique-mcp>=0.1.1",
    "unique-toolkit>=1.42.8",
]

[project.scripts]
console-agent = "console_agent:main"

[build-system]
requires = ["uv_build>=0.8.23,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.37.1",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.11",
]
