site_name: Unique SDK
site_description: Documentation for the Unique SDK
site_author: Unique Team
site_url: https://github.com/Unique-AG/ai/unique_sdk
repo_name: Unique-AG/ai/unique_sdk
repo_url: https://github.com/Unique-AG/ai/unique_sdk  
edit_uri: /docs/

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - Configuration: getting_started/configuration.md
    - Quickstart: getting_started/quickstart.md
  - Architecture:
    - Overview: architecture.md
  - API Reference:
    - Overview: api_resources/index.md
    - Agentic Table: api_resources/agentic_table.md
    - ChatCompletion: api_resources/chat_completion.md
    - Content: api_resources/content.md
    - Embeddings: api_resources/embeddings.md
    - Folder: api_resources/folder.md
    - Group: api_resources/group.md
    - LLM Models: api_resources/llm_models.md
    - Message: api_resources/message.md
    - Message Assessment: api_resources/message_assessment.md
    - Message Execution: api_resources/message_execution.md
    - Message Log: api_resources/message_log.md
    - Search: api_resources/search.md
    - SearchString: api_resources/search_string.md
    - Short Term Memory: api_resources/short_term_memory.md
    - Space: api_resources/space.md
    - User: api_resources/user.md
  - UniqueQL:
    - Query Language: uniqueql.md
  - Utilities:
    - Chat History: utilities/chat_history.md
    - File I/O: utilities/file_io.md
    - Sources: utilities/sources.md
    - Token Management: utilities/token.md
    - Chat in Space: utilities/chat_in_space.md
  - Webhooks:
    - Overview: webhooks.md
  - Tutorials:
    - Folder Updates: tutorials/folder_updates.md
    - Rule-Based Search: tutorials/get_contents.md
    - OpenAI Integration: tutorials/openai_scripts.md


markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - attr_list

docs_dir: docs
site_dir: site

plugins:
  - search
  - include-dir-to-nav:
      flat: true
      file_name_as_title: false
      recurse: false
      file_pattern: '.*\.md$'
  - entangled
  - include-markdown 
  - callouts
  - codeinclude
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            show_root_heading: true
            show_source: true
            filters:
              - "!.[company|user|assistant|chat|assistant_id|assistant_message_id|user_message_id]_id.*"
              - "!.*_async.*"
              - "!.*event.*"
            extra:
              show_signature_annotations: true
              show_type_annotations: true
              show_if_no_docstring: false