[tool.poetry]
name = "unique_six"
version = "0.1.0"
description = "Unique Six API client"
authors = [
    "Ahmed Jellouli <ahmed.jellouli.ext@unique.ch>",
    "Azeez Raheem <azeez.raheem.ext@unique.ai>"
]
readme = ["README.md", "CHANGELOG.md"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.12.4"
python-dotenv = "^1.0.1"
unique-toolkit = "^1.38.3"
cryptography = "^45.0.6"

[tool.poetry.group.dev.dependencies]
ruff = "0.12.10"
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
unique-toolkit = { path = "../../unique_toolkit",  develop = true }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = ["I"]
