name: "[unique_search_proxy ðŸ§ª] Publish Proxy"

on:
  push:
    branches:
      - main
    paths:
      - connectors/unique_search_proxy/**
      - .github/workflows/publish_connector_unique_search_proxy.yaml
  pull_request:
    branches:
      - main
    paths:
      - connectors/unique_search_proxy/**
      - .github/workflows/publish_connector_unique_search_proxy.yaml

jobs:
  containerize:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      packages: write
    env:
      CHART_REPO: ghcr.io/unique-ag/ai/search-proxy

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Add docker metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.CHART_REPO }}
          tags: |
            type=sha,suffix=-experimental,format=short

      - name: Login to registry hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          cache-from: type=registry,ref=${{ env.CHART_REPO }}:cache
          cache-to: type=registry,ref=${{ env.CHART_REPO }}:cache,mode=min
          context: connectors/unique_search_proxy
          file: connectors/unique_search_proxy/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          provenance: false
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
